name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: |
      startsWith(github.event.head_commit.message, 'chore(main): release')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying"